"""Light smoke test for the golden-fixture set generated by
tools/generate_fixtures.py: every fixture file must exist, load with
np.load(), and contain the keys the generator promises. This is deliberately
*not* a correctness test (it needs no madmom_infer port code to exist yet) --
its only job is to catch a broken/partial/corrupted fixture set early, before
any port's own golden-fixture tests try to load these files and get a
confusing failure instead.

Reads: tests/fixtures/*.npz, tests/fixtures/manifest.json (written by
tools/generate_fixtures.py); read by: pytest
"""

import json
from pathlib import Path

import numpy as np
import pytest

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

EXPECTED_KEYS = {
    "signal.npz": {
        f"{case}_{suffix}"
        for case in (
            "mono_44100",
            "stereo_44100",
            "stereo_48000",
            "float32_44100",
        )
        for suffix in (
            "raw",
            "raw_sample_rate",
            "mono",
            "mono_sample_rate",
            "fromarray",
            "fromarray_sample_rate",
        )
    },
    "framing.npz": {
        f"{case}_{suffix}"
        for case in (
            "mono_44100",
            "stereo_44100",
            "stereo_48000",
            "float32_44100",
        )
        for suffix in (
            "num_frames",
            "frame_size",
            "hop_size",
            "frame0",
            "frame1",
            "frame_last",
            "all_frames_sha256",
        )
    },
    "stft.npz": {
        f"{case}_stft_{suffix}"
        for case in (
            "mono_44100",
            "stereo_44100_mono",
            "stereo_48000_mono",
            "float32_44100",
        )
        for suffix in ("frame0", "frame1", "frame_last", "all_sha256")
    }
    | {
        "window_caching_reused_output",
        "window_caching_fresh_output",
        "window_caching_max_abs_diff",
    },
    "filterbank.npz": {
        "filterbank_matrix_44100",
        "filterbank_matrix_48000",
    }
    | {
        f"{case}_filtered_{suffix}"
        for case in ("mono_44100", "stereo_48000_mono")
        for suffix in ("frame0", "frame1", "frame_last", "all_sha256")
    },
    "logspec.npz": {
        f"{case}_logspec_{suffix}"
        for case in ("mono_44100", "stereo_48000_mono")
        for suffix in ("frame0", "frame1", "frame_last", "all_sha256")
    },
    "full_chain.npz": {
        f"{case}_{suffix}"
        for case in (
            "mono_44100",
            "stereo_44100_mono",
            "stereo_48000_mono",
            "float32_44100",
        )
        for suffix in ("frame0", "frame1", "frame_last", "num_frames", "all_sha256")
    },
    "hmm_toy.npz": {
        "dense_transition_matrix",
        "tm_states",
        "tm_pointers",
        "tm_probabilities",
        "observation_probabilities",
        "observation_sequence",
        "viterbi_path",
        "viterbi_log_prob",
        "forward_output",
    },
    "beats_hmm.npz": {
        f"bpb{n}_{suffix}"
        for n in (3, 4)
        for suffix in (
            "num_states",
            "num_beats",
            "first_states",
            "last_states",
            "tm_num_states",
            "tm_num_transitions",
            "tm_states",
            "tm_pointers",
            "tm_probabilities",
            "om_pointers",
        )
    },
    "dbn_downbeat.npz": {"activations", "beat_times"},
}


@pytest.mark.parametrize("filename", sorted(EXPECTED_KEYS))
def test_fixture_file_exists_and_loads(filename):
    path = FIXTURES_DIR / filename
    assert path.is_file(), f"missing fixture file: {path}"
    with np.load(path) as data:
        actual_keys = set(data.files)
        expected_keys = EXPECTED_KEYS[filename]
        missing = expected_keys - actual_keys
        assert not missing, f"{filename} is missing expected keys: {sorted(missing)}"


def test_wav_fixtures_exist():
    wavs_dir = FIXTURES_DIR / "wavs"
    expected = {
        "mono_44100.wav",
        "stereo_44100.wav",
        "stereo_48000.wav",
        "float32_44100.wav",
    }
    actual = {p.name for p in wavs_dir.glob("*.wav")}
    missing = expected - actual
    assert not missing, f"missing test wavs: {sorted(missing)}"


def test_manifest_exists_and_has_provenance():
    manifest_path = FIXTURES_DIR / "manifest.json"
    assert manifest_path.is_file(), f"missing manifest: {manifest_path}"
    manifest = json.loads(manifest_path.read_text())
    for key in (
        "madmom_version",
        "madmom_commit",
        "numpy_version",
        "scipy_version",
        "generation_command",
        "fixture_files",
    ):
        assert key in manifest, f"manifest.json missing key: {key}"
    assert manifest["madmom_version"], "manifest.json: madmom_version is empty"
