"""Light smoke test for the golden-fixture set generated by
tools/generate_fixtures.py: every fixture file must exist, load with
np.load(), and contain the keys the generator promises. This is deliberately
*not* a correctness test (it needs no madmom_infer port code to exist yet) --
its only job is to catch a broken/partial/corrupted fixture set early, before
any port's own golden-fixture tests try to load these files and get a
confusing failure instead.

Reads: tests/fixtures/*.npz, tests/fixtures/manifest.json (written by
tools/generate_fixtures.py); read by: pytest
"""

import json
from pathlib import Path

import numpy as np
import pytest

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

EXPECTED_KEYS = {
    "signal.npz": {
        f"{case}_{suffix}"
        for case in (
            "mono_44100",
            "stereo_44100",
            "stereo_48000",
            "float32_44100",
        )
        for suffix in (
            "raw",
            "raw_sample_rate",
            "mono",
            "mono_sample_rate",
            "fromarray",
            "fromarray_sample_rate",
        )
    },
    "framing.npz": {
        f"{case}_{suffix}"
        for case in (
            "mono_44100",
            "stereo_44100",
            "stereo_48000",
            "float32_44100",
        )
        for suffix in (
            "num_frames",
            "frame_size",
            "hop_size",
            "frame0",
            "frame1",
            "frame_last",
            "all_frames_sha256",
        )
    },
    "stft.npz": {
        f"{case}_stft_{suffix}"
        for case in (
            "mono_44100",
            "stereo_44100_mono",
            "stereo_48000_mono",
            "float32_44100",
        )
        for suffix in ("frame0", "frame1", "frame_last", "all_sha256")
    }
    | {
        "window_caching_reused_output",
        "window_caching_fresh_output",
        "window_caching_max_abs_diff",
    },
    "filterbank.npz": {
        "filterbank_matrix_44100",
        "filterbank_matrix_48000",
    }
    | {
        f"{case}_filtered_{suffix}"
        for case in ("mono_44100", "stereo_48000_mono")
        for suffix in ("frame0", "frame1", "frame_last", "all_sha256")
    },
    "logspec.npz": {
        f"{case}_logspec_{suffix}"
        for case in ("mono_44100", "stereo_48000_mono")
        for suffix in ("frame0", "frame1", "frame_last", "all_sha256")
    },
    "full_chain.npz": {
        f"{case}_{suffix}"
        for case in (
            "mono_44100",
            "stereo_44100_mono",
            "stereo_48000_mono",
            "float32_44100",
        )
        for suffix in ("frame0", "frame1", "frame_last", "num_frames", "all_sha256")
    },
    "hmm_toy.npz": {
        "dense_transition_matrix",
        "tm_states",
        "tm_pointers",
        "tm_probabilities",
        "observation_probabilities",
        "observation_sequence",
        "viterbi_path",
        "viterbi_log_prob",
        "forward_output",
    },
    "beats_hmm.npz": {
        f"bpb{n}_{suffix}"
        for n in (3, 4)
        for suffix in (
            "num_states",
            "num_beats",
            "first_states",
            "last_states",
            "tm_num_states",
            "tm_num_transitions",
            "tm_states",
            "tm_pointers",
            "tm_probabilities",
            "om_pointers",
        )
    },
    "dbn_downbeat.npz": {"activations", "beat_times"},
    # Phase 2 (tools/generate_phase2_fixtures.py) -- 44.1kHz-native cases
    # only, RNNDownBeatProcessor has no resampling support (see that file's
    # module header).
    "rnn_downbeat.npz": {
        f"{case}_{suffix}"
        for case in ("mono_44100", "stereo_44100", "float32_44100")
        for suffix in ("activations", "beat_times")
    },
    # Wave 4a (tools/generate_key_fixtures.py) -- 44.1kHz-native cases only,
    # CNNKeyRecognitionProcessor has no resampling support (same reason as
    # RNNDownBeatProcessor, see that file's module header).
    "key_layers.npz": {"spec_input"} | {
        f"{layer_type}_{suffix}"
        for layer_type, suffixes in (
            ("PadLayer", ("input", "output")),
            ("ConvolutionalLayer", ("input", "output", "weights", "bias")),
            ("BatchNormLayer",
             ("input", "output", "beta", "gamma", "mean", "inv_std")),
            ("MaxPoolLayer", ("input", "output")),
            ("AverageLayer", ("input", "output")),
        )
        for suffix in suffixes
    },
    "key_activations.npz": {
        f"{case}_{suffix}"
        for case in ("mono_44100", "stereo_44100", "float32_44100")
        for suffix in ("prediction", "label")
    },
    # Wave 4b (tools/generate_onset_fixtures.py) -- pure-DSP onset function
    # golden outputs, model-independent (mono_44100.wav only, see that
    # file's module header).
    "onset_dsp_functions.npz": {
        "wrap_to_pi_input", "wrap_to_pi_output", "high_frequency_content",
        "spectral_diff", "spectral_flux", "superflux",
        "modified_kullback_leibler", "phase_deviation",
        "weighted_phase_deviation", "normalized_weighted_phase_deviation",
        "complex_domain", "rectified_complex_domain",
        "complex_flux_unfiltered", "complex_flux_filtered", "sodf_default",
        "sodf_superflux",
    },
    "onset_stride_layer.npz": {"StrideLayer_input", "StrideLayer_output"},
    # Wave 4b -- 44.1kHz-native cases only, RNNOnsetProcessor/
    # CNNOnsetProcessor have no resampling support (same reason as
    # RNNDownBeatProcessor/CNNKeyRecognitionProcessor).
    "onset_activations.npz": {
        f"{case}_{model}_{suffix}"
        for case in ("mono_44100", "stereo_44100", "float32_44100")
        for model in ("brnn", "rnn", "cnn")
        for suffix in ("activations", "onsets")
    },
    # Wave 4c (tools/generate_beat_tempo_fixtures.py) -- comb-filter
    # function fixtures, fed a real beat activation function
    # (mono_44100.wav only, see that file's module header).
    "beats_comb_filters.npz": {
        "comb_filter_input_1d", "comb_filter_input_2d",
        "comb_filter_bank_forward", "comb_filter_bank_backward",
    } | {
        f"feed_{direction}_tau{tau}"
        for direction in ("forward", "backward")
        for tau in (5, 17, 43)
    } | {"feed_backward_2d_tau17"},
    # Wave 4c -- 44.1kHz-native cases only, RNNBeatProcessor has no
    # resampling support (same reason as RNNDownBeatProcessor/
    # RNNOnsetProcessor).
    "beats_activations.npz": {
        f"{case}_{model}_{suffix}"
        for case in ("mono_44100", "stereo_44100", "float32_44100")
        for model in ("blstm", "lstm")
        for suffix in ("activations", "beat_times")
    },
    "beats_multimodel_selection.npz": {
        f"prediction_{i}" for i in range(8)
    } | {"selected"},
    "tempo_histograms.npz": {"tempo_input_activations"} | {
        f"{method}_{suffix}"
        for method in ("acf", "comb", "dbn")
        for suffix in ("histogram_bins", "histogram_delays", "tempi")
    },
    "sync_features.npz": {
        "sync_features_input", "sync_beats_input", "sync_features_output",
    },
    "downbeats_bgru_intermediate.npz": {
        "beats", "perc_synced", "harm_synced", "perc_nn_out", "harm_nn_out",
        "full_downbeat_activation",
    },
    # Wave 4d (tools/generate_chroma_chord_fixtures.py) -- CRF direct-decode
    # fixture, real chord-feature observations + real decoded state
    # sequence + labels, both CRF model families.
    "crf_decode.npz": {
        "dccrf_observations", "dccrf_y_star", "dccrf_labels_start",
        "dccrf_labels_end", "dccrf_labels_label", "cfcrf_observations",
        "cfcrf_y_star", "cfcrf_labels_start", "cfcrf_labels_end",
        "cfcrf_labels_label",
    },
    # Wave 4d -- classic chroma (PitchClassProfile/HarmonicPitchClassProfile),
    # 44.1kHz-native cases only (no file-load resampling).
    "chroma_classic.npz": {
        f"{case}_{suffix}"
        for case in ("mono_44100", "stereo_44100", "float32_44100")
        for suffix in ("pcp", "hpcp")
    },
    # Wave 4d -- CLP chroma (SemitoneBandpassSpectrogram + CLPChroma).
    "clp_chroma.npz": {
        f"{case}_{suffix}"
        for case in ("mono_44100", "stereo_44100", "float32_44100")
        for suffix in (
            "semitone_bandpass", "semitone_bin_frequencies", "clp_chroma",
        )
    },
    # Wave 4d -- DeepChromaProcessor end-to-end activations.
    "chroma_dnn_activations.npz": {
        f"{case}_chroma"
        for case in ("mono_44100", "stereo_44100", "float32_44100")
    },
    # Wave 4d -- chord recognition end-to-end (audio -> chord segments),
    # both DeepChromaChordRecognitionProcessor (dccrf) and
    # CNNChordFeatureProcessor + CRFChordRecognitionProcessor (cfcrf) paths.
    "chords_end_to_end.npz": {
        f"{case}_{model}_{suffix}"
        for case in ("mono_44100", "stereo_44100", "float32_44100")
        for model in ("dccrf", "cfcrf")
        for suffix in ("start", "end", "label")
    },
    # Wave 4d -- RNNBarProcessor full AUDIO-IN end-to-end fixture.
    "rnn_bar_end_to_end.npz": {
        f"{case}_{suffix}"
        for case in ("mono_44100", "stereo_44100", "float32_44100")
        for suffix in ("beats", "bar_output")
    },
}


@pytest.mark.parametrize("filename", sorted(EXPECTED_KEYS))
def test_fixture_file_exists_and_loads(filename):
    path = FIXTURES_DIR / filename
    assert path.is_file(), f"missing fixture file: {path}"
    with np.load(path) as data:
        actual_keys = set(data.files)
        expected_keys = EXPECTED_KEYS[filename]
        missing = expected_keys - actual_keys
        assert not missing, f"{filename} is missing expected keys: {sorted(missing)}"


def test_nn_structural_digest_exists_and_loads():
    """Phase 2 fixture (tools/generate_phase2_fixtures.py): the unpickled-
    model structural digest for all 8 DOWNBEATS_BLSTM ensemble networks."""
    path = FIXTURES_DIR / "nn_structural_digest.json"
    assert path.is_file(), f"missing fixture file: {path}"
    digest = json.loads(path.read_text())
    expected_keys = {f"downbeats_blstm_{i}" for i in range(1, 9)}
    missing = expected_keys - set(digest.keys())
    assert not missing, f"nn_structural_digest.json missing keys: {sorted(missing)}"


def test_key_structural_digest_exists_and_loads():
    """Wave 4a fixture (tools/generate_key_fixtures.py): the unpickled
    key_cnn.pkl structural digest."""
    path = FIXTURES_DIR / "key_structural_digest.json"
    assert path.is_file(), f"missing fixture file: {path}"
    digest = json.loads(path.read_text())
    assert "key_cnn" in digest, "key_structural_digest.json missing 'key_cnn'"
    assert len(digest["key_cnn"]) == 30, (
        "key_cnn.pkl is expected to have exactly 30 layers"
    )


def test_key_layer_params_exists_and_loads():
    """Wave 4a fixture (tools/generate_key_fixtures.py): non-array
    hyperparameters for each of the 5 new layer-type fixtures in
    key_layers.npz."""
    path = FIXTURES_DIR / "key_layer_params.json"
    assert path.is_file(), f"missing fixture file: {path}"
    params = json.loads(path.read_text())
    expected_types = {
        "PadLayer", "ConvolutionalLayer", "BatchNormLayer", "MaxPoolLayer",
        "AverageLayer",
    }
    missing = expected_types - set(params.keys())
    assert not missing, f"key_layer_params.json missing types: {sorted(missing)}"


def test_onset_structural_digest_exists_and_loads():
    """Wave 4b fixture (tools/generate_onset_fixtures.py): the unpickled
    onsets_rnn_1/onsets_brnn_1/onsets_cnn structural digests."""
    path = FIXTURES_DIR / "onset_structural_digest.json"
    assert path.is_file(), f"missing fixture file: {path}"
    digest = json.loads(path.read_text())
    expected_keys = {"onsets_rnn_1", "onsets_brnn_1", "onsets_cnn"}
    missing = expected_keys - set(digest.keys())
    assert not missing, f"onset_structural_digest.json missing keys: {sorted(missing)}"
    assert len(digest["onsets_rnn_1"]) == 4
    assert len(digest["onsets_brnn_1"]) == 4
    assert len(digest["onsets_cnn"]) == 8


def test_onset_stride_layer_params_exists_and_loads():
    """Wave 4b fixture (tools/generate_onset_fixtures.py): StrideLayer's
    non-array hyperparameter (block_size)."""
    path = FIXTURES_DIR / "onset_stride_layer_params.json"
    assert path.is_file(), f"missing fixture file: {path}"
    params = json.loads(path.read_text())
    assert "StrideLayer" in params
    assert "block_size" in params["StrideLayer"]


def test_beats_structural_digest_exists_and_loads():
    """Wave 4c fixture (tools/generate_beat_tempo_fixtures.py): the
    unpickled beats_lstm_1/beats_blstm_1 structural digests."""
    path = FIXTURES_DIR / "beats_structural_digest.json"
    assert path.is_file(), f"missing fixture file: {path}"
    digest = json.loads(path.read_text())
    expected_keys = {"beats_lstm_1", "beats_blstm_1"}
    missing = expected_keys - set(digest.keys())
    assert not missing, f"beats_structural_digest.json missing keys: {sorted(missing)}"
    assert len(digest["beats_lstm_1"]) == 4
    assert len(digest["beats_blstm_1"]) == 4


def test_downbeats_bgru_structural_digest_exists_and_loads():
    """Wave 4c fixture (tools/generate_beat_tempo_fixtures.py): the
    unpickled downbeats_bgru_rhythmic_0/harmonic_0 structural digests
    (GRULayer/GRUCell)."""
    path = FIXTURES_DIR / "downbeats_bgru_structural_digest.json"
    assert path.is_file(), f"missing fixture file: {path}"
    digest = json.loads(path.read_text())
    expected_keys = {
        "downbeats_bgru_rhythmic_0", "downbeats_bgru_harmonic_0",
    }
    missing = expected_keys - set(digest.keys())
    assert not missing, (
        f"downbeats_bgru_structural_digest.json missing keys: {sorted(missing)}"
    )
    assert len(digest["downbeats_bgru_rhythmic_0"]) == 3
    assert len(digest["downbeats_bgru_harmonic_0"]) == 3


def test_wav_fixtures_exist():
    wavs_dir = FIXTURES_DIR / "wavs"
    expected = {
        "mono_44100.wav",
        "stereo_44100.wav",
        "stereo_48000.wav",
        "float32_44100.wav",
    }
    actual = {p.name for p in wavs_dir.glob("*.wav")}
    missing = expected - actual
    assert not missing, f"missing test wavs: {sorted(missing)}"


def test_manifest_exists_and_has_provenance():
    manifest_path = FIXTURES_DIR / "manifest.json"
    assert manifest_path.is_file(), f"missing manifest: {manifest_path}"
    manifest = json.loads(manifest_path.read_text())
    for key in (
        "madmom_version",
        "madmom_commit",
        "numpy_version",
        "scipy_version",
        "generation_command",
        "fixture_files",
    ):
        assert key in manifest, f"manifest.json missing key: {key}"
    assert manifest["madmom_version"], "manifest.json: madmom_version is empty"


def test_chroma_dnn_structural_digest_exists_and_loads():
    """Wave 4d fixture (tools/generate_chroma_chord_fixtures.py): the
    unpickled chroma_dnn.pkl structural digest."""
    path = FIXTURES_DIR / "chroma_dnn_structural_digest.json"
    assert path.is_file(), f"missing fixture file: {path}"
    digest = json.loads(path.read_text())
    assert "chroma_dnn" in digest, (
        "chroma_dnn_structural_digest.json missing 'chroma_dnn'"
    )
    assert len(digest["chroma_dnn"]) == 4, (
        "chroma_dnn.pkl is expected to have exactly 4 FeedForwardLayers"
    )
